version: '3'

services:

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 3000:3000

  apache2:
    build:
      context: ./
      dockerfile: ./docker/apache2/Dockerfile
    ports:
      - 3001:3000
